name: Personeelsverloop1
favicon: null
layout_spectrum: 0.35701483068987727
typography_spectrum: 0.7850966101977974
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.14440684602595866
  lightness: 0.7290200118441135
  saturation: 0.40745723620057106
  rhythmicContrast: 0.6366021977737546
purpose: []
