name: Personeelsverloop1
favicon: null
layout_spectrum: 0.35701483068987727
typography_spectrum: 0.58306
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a8a499'
    - '#d5cbbf'
    - '#4c4c4c'
    - '#09922e'
  brandStrength: 0.14440684602595866
  lightness: 0.9375
  saturation: 0.40745723620057106
  rhythmicContrast: 0.6366021977737546
purpose: []
