name: Personeelsverloop1
favicon: null
layout_spectrum: 0.34705
typography_spectrum: 0.41349
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a8a499'
    - '#d5cbbf'
    - '#4c4c4c'
    - '#09922e'
  brandStrength: 0.8125
  lightness: 0.9375
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
